# Generated by Django 5.0.7 on 2024-07-23 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together=set(),
        ),
    ]
